#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          cDistro
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/Stop web configuration server
### END INIT INFO

NAME=cdistro
CONFFILE="/etc/cloudy/cloudy.conf"
PIDFILE="/var/run/cdistro.pid"
PIDDAEMON="/var/run/cdistrod.pid"
DAEMON="/usr/sbin/cdistrod"

DEMO=0

test -f $CONFFILE && . $CONFFILE || exit 0

start() {
  echo "Starting cDistro"
  if [ $DEMO -eq 1 ]; then
    su - nobody -c "$SERVER $OPTS -S $BINDIP:$PORT -t $DOCROOT >/dev/null 2>&1 &" > /dev/null 2>&1
    echo $(pidof php) > $PIDFILE
  else
    $SERVER $OPTS -S $BINDIP:$PORT -t $DOCROOT >/dev/null 2>&1 &
    echo $! > $PIDFILE
  fi
  $DAEMON >/dev/null 2>&1 &
  echo $! > $PIDDAEMON
}

stop() {
  [ -f $PIDFILE ] && echo "Stopping cDistro. Sending terminate signal to process $(cat $PIDFILE)..." && kill -15 $(cat $PIDFILE) && sleep 1
  $(netstat -ant|grep ${BINDIP}|grep ${PORT}|grep -q LISTEN) && echo "Stopping cDistro. Sending interrupt signal to process $(cat $PIDFILE)..." && kill -2 $(cat $PIDFILE) && sleep 1
  $(netstat -ant|grep ${BINDIP}|grep ${PORT}|grep -q LISTEN) && echo "Stopping cDistro. Sending kill signal to process $(cat $PIDFILE)..." && kill -9 $(cat $PIDFILE) && sleep 1
  ! $(netstat -ant|grep ${BINDIP}|grep ${PORT}|grep -q LISTEN) && [ -f $PIDFILE ] && rm $PIDFILE

  [ -f $PIDDAEMON ] && echo "Stopping cDistro. Sending terminate signal to process $(cat $PIDDAEMON)..." && kill -15 $(cat $PIDDAEMON) && sleep 1
  [ -f $PIDDAEMON ] && kill -0  $(cat $PIDDAEMON) >/dev/null 2>&1 && echo "Stopping cDistro. Sending interrupt signal to process $(cat $PIDDAEMON)..." && kill -2 $(cat $PIDDAEMON) && sleep 1
  [ -f $PIDDAEMON ] && kill -0  $(cat $PIDDAEMON) >/dev/null 2>&1 && echo "Stopping cDistro. Sending kill signal to process $(cat $PIDDAEMON)..." && kill -9 $(cat $PIDDAEMON) && sleep 1
  [ -f $PIDDAEMON ] && ! kill -0  $(cat $PIDDAEMON) >/dev/null 2>&1 && [ -f $PIDDAEMON ] && rm $PIDDAEMON
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
  ;;
esac

exit 0
