<?php

addS("menus_cloudy_https", "HTTP/HTTPS server");
addS("https_title", "HTTP/HTTPS server");
addS("https_subtitle", "Cloudy web interface security management");
addS("https_desc", "Use this page to configure the security settings of your Cloudy instance. When HTTPS is enabled, the connection between your browser and the Cloudy web interface is secured by an autogenerated TLS certificate.");
addS("https_status", "Web interface status:");
addS("https_recommend", "Suggestion:");
addS("https_recommendation", "Use HTTPS instead of HTTP whenever you can ;)");
addS("https_is_not_installed", "HTTPS is not enabled");
addS("https_install", "Enable HTTPS only (recommended)");
addS("https_install_both", "Enable both HTTP and HTTPS");
addS("https_is_installed", "HTTPS is enabled");
addS("https_remove", "Disable HTTPS");
addS("https_enable", "After enabling HTTPS, you will be redirected to the new web interface. If the page is not shown, try reloading it after a few seconds.");
addS("https_disable", "After disabling HTTPS, you will be redirected to the new web interface. If the page is not shown, try reloading it after a few seconds.");
addS("https_already_enabled", "HTTPS is already enabled");
addS("https_not_enabled_yet", "HTTPS is not enabled yet");
